// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService is the single Wails entry point for commands generated by
 * the Tauri frontend. It routes operations through the shared Runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

export function Invoke(command: string, argsJSON: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(963551315, command, argsJSON);
}
