// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function OpenDirectory(options: $models.OpenDirectoryOptions): $CancellablePromise<any> {
    return $Call.ByID(431777850, options);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(699720300, url);
}

export function RevealItemInDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(864414793, path);
}
