package backend

import (
	"encoding/json"
	"errors"
	"fmt"
)

// CommandService is the single Wails entry point for commands generated by
// the Tauri frontend. It routes operations through the shared Runtime.
type CommandService struct {
	Runtime *Runtime
}

var commandHandlers = map[string]func(*CommandService, json.RawMessage) (json.RawMessage, error){
	"list_contexts": func(service *CommandService, args json.RawMessage) (json.RawMessage, error) {
		if err := requireEmptyObject(args); err != nil {
			return nil, fmt.Errorf("invalid arguments for list_contexts: %w", err)
		}
		if service.Runtime == nil {
			return nil, errors.New("runtime is not configured")
		}
		contexts, err := service.Runtime.ListContexts()
		if err != nil {
			return nil, err
		}
		encoded, err := json.Marshal(JSONSlice[Context](contexts))
		if err != nil {
			return nil, fmt.Errorf("encode list_contexts result: %w", err)
		}
		return encoded, nil
	},
}

var registeredCommandArguments = map[string][]string{
	"list_contexts": {},
}

func (s *CommandService) Invoke(command string, argsJSON string) (json.RawMessage, error) {
	args := json.RawMessage(argsJSON)
	if len(args) == 0 {
		args = json.RawMessage(`{}`)
	}
	handler, ok := commandHandlers[command]
	if !ok {
		return nil, fmt.Errorf("unknown command: %s", command)
	}
	return handler(s, args)
}

func requireEmptyObject(raw json.RawMessage) error {
	var args map[string]json.RawMessage
	if err := json.Unmarshal(raw, &args); err != nil {
		return err
	}
	if args == nil {
		return errors.New("expected an object")
	}
	if len(args) != 0 {
		return errors.New("command takes no arguments")
	}
	return nil
}
