package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"

	"github.com/piero/ai-mission-manager-wails/backend/domain"
)

// CommandService is the single Wails entry point for commands generated by
// the Tauri frontend. It routes operations through the shared Runtime.
type CommandService struct{ Runtime *Runtime }
type commandHandler func(*CommandService, json.RawMessage) (json.RawMessage, error)

var commandHandlers = map[string]commandHandler{
	"list_grill_model_catalog": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listGrillModelCatalog()
	}),
	"refresh_grill_model_catalog": noArgs(func(s *CommandService) (any, error) {
		if writable(s) {
			s.Runtime.refreshGrillModelCatalog()
		}
		return nil, nil
	}),
	"list_plan_usage": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listPlanUsage()
	}),
	"refresh_plan_usage": noArgs(func(s *CommandService) (any, error) {
		if writable(s) {
			s.Runtime.refreshPlanUsage()
		}
		return nil, nil
	}),
	"get_setup_state": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.setupState()
	}),
	"complete_setup": withArgs([]string{"contextName", "provider"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextName string         `json:"contextName"`
			Provider    ProviderChoice `json:"provider"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.completeSetup(a.ContextName, a.Provider)
	}),
	"get_health_status": withArgs([]string{"provider"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Provider *ProviderChoice `json:"provider"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.healthStatus(a.Provider)
	}),
	"list_contexts": noArgs(func(s *CommandService) (any, error) {
		if s.Runtime == nil {
			return nil, errors.New("runtime is not configured")
		}
		v, e := s.Runtime.ListContexts()
		if v == nil {
			v = []Context{}
		}
		return v, e
	}),
	"new_context_configuration": noArgs(func(*CommandService) (any, error) { return defaultContextConfiguration(), nil }),
	"list_context_attention_defaults": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		v := s.Runtime.listAttentionDefaults()
		if v == nil {
			v = []domain.ContextAttentionDefault{}
		}
		return v, nil
	}),
	"list_projects": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		v := s.Runtime.listProjects()
		return v, nil
	}),
	"list_repositories": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listRepositories(), nil
	}),
	"list_repository_locations": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listRepositoryLocations(), nil
	}),
	"register_repository": withArgs([]string{"projectId", "name", "remoteUrl"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ProjectID int64  `json:"projectId"`
			Name      string `json:"name"`
			RemoteURL string `json:"remoteUrl"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.registerRepository(a.ProjectID, a.Name, a.RemoteURL)
	}),
	"update_repository": withArgs([]string{"repositoryId", "name", "remoteUrl", "baseBranch"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			RepositoryID int64  `json:"repositoryId"`
			Name         string `json:"name"`
			RemoteURL    string `json:"remoteUrl"`
			BaseBranch   string `json:"baseBranch"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.updateRepository(a.RepositoryID, a.Name, a.RemoteURL, a.BaseBranch)
	}),
	"register_repository_at_location": withArgs([]string{"projectId", "name", "remoteUrl", "baseBranch", "machineId", "checkoutPath", "worktreeRoot", "cloneIntoDestination"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ProjectID            int64   `json:"projectId"`
			Name                 string  `json:"name"`
			RemoteURL            *string `json:"remoteUrl"`
			BaseBranch           string  `json:"baseBranch"`
			MachineID            int64   `json:"machineId"`
			CheckoutPath         string  `json:"checkoutPath"`
			WorktreeRoot         *string `json:"worktreeRoot"`
			CloneIntoDestination bool    `json:"cloneIntoDestination"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.registerRepositoryAtLocation(a.ProjectID, a.Name, a.RemoteURL, a.BaseBranch, a.MachineID, a.CheckoutPath, a.WorktreeRoot, a.CloneIntoDestination)
	}),
	"update_repository_location": withArgs([]string{"repositoryId", "previousMachineId", "machineId", "checkoutPath", "worktreeRoot"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			RepositoryID      int64  `json:"repositoryId"`
			PreviousMachineID *int64 `json:"previousMachineId"`
			MachineID         int64  `json:"machineId"`
			CheckoutPath      string `json:"checkoutPath"`
			WorktreeRoot      string `json:"worktreeRoot"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.updateRepositoryLocation(a.RepositoryID, a.PreviousMachineID, a.MachineID, a.CheckoutPath, a.WorktreeRoot)
	}),
	"list_machines": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listMachines(), nil
	}),
	"list_cli_configuration_profiles": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listCLIConfigurationProfiles(), nil
	}),
	"register_machine": withArgs([]string{"contextId", "name", "socketName", "transport"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID  int64                   `json:"contextId"`
			Name       string                  `json:"name"`
			SocketName string                  `json:"socketName"`
			Transport  domain.MachineTransport `json:"transport"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.registerMachine(a.ContextID, a.Name, a.SocketName, a.Transport)
	}),
	"update_machine": withArgs([]string{"machineId", "name", "socketName", "transport"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			MachineID  int64                   `json:"machineId"`
			Name       string                  `json:"name"`
			SocketName string                  `json:"socketName"`
			Transport  domain.MachineTransport `json:"transport"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.updateMachine(a.MachineID, a.Name, a.SocketName, a.Transport)
	}),
	"check_machine": withArgs([]string{"machineId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			MachineID int64 `json:"machineId"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.checkMachine(a.MachineID)
	}),
	"set_context_execution_machine": withArgs([]string{"contextId", "machineId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64  `json:"contextId"`
			MachineID *int64 `json:"machineId"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.setContextExecutionMachine(a.ContextID, a.MachineID)
	}),
	"create_cli_configuration_profile": withArgs([]string{"machineId", "provider", "name", "appManaged", "existingDirectory"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			MachineID         int64            `json:"machineId"`
			Provider          domain.AgentKind `json:"provider"`
			Name              string           `json:"name"`
			AppManaged        bool             `json:"appManaged"`
			ExistingDirectory *string          `json:"existingDirectory"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.createCLIConfigurationProfile(a.MachineID, a.Provider, a.Name, a.AppManaged, a.ExistingDirectory)
	}),
	"delete_cli_configuration_profile": withArgs([]string{"profileId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ProfileID int64 `json:"profileId"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return nil, s.Runtime.deleteCLIConfigurationProfile(a.ProfileID)
	}),
	"set_context_cli_configuration_profile": withArgs([]string{"contextId", "provider", "profileId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64            `json:"contextId"`
			Provider  domain.AgentKind `json:"provider"`
			ProfileID *int64           `json:"profileId"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.setContextCLIConfigurationProfile(a.ContextID, a.Provider, a.ProfileID)
	}),
	"list_audit_history": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listAuditHistory(), nil
	}),
	"get_activity_tab": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.activityTab(), nil
	}),
	"get_home": withArgs([]string{"contextId", "now"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID *int64 `json:"contextId"`
			Now       string `json:"now"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.home(a.ContextID, a.Now), nil
	}),
	"search_items_command": withArgs([]string{"query", "contextId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Query     string `json:"query"`
			ContextID *int64 `json:"contextId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.searchItems(a.Query, a.ContextID), nil
	}),
	"list_inbox_items": noArgs(func(s *CommandService) (any, error) {
		if !writable(s) {
			return nil, errors.New("runtime is not configured")
		}
		return s.Runtime.listInboxItems(), nil
	}),
	"create_context": withArgs([]string{"name"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Name string `json:"name"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "create_context", Name: a.Name})
	}),
	"create_context_configuration": withArgs([]string{"configuration"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Configuration domain.ContextConfiguration `json:"configuration"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "create_context_configuration", Configuration: a.Configuration})
	}),
	"update_context": withArgs([]string{"contextId", "name"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64  `json:"contextId"`
			Name      string `json:"name"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "update_context", ContextID: a.ContextID, Name: a.Name})
	}),
	"update_context_configuration": withArgs([]string{"contextId", "configuration"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID     int64                       `json:"contextId"`
			Configuration domain.ContextConfiguration `json:"configuration"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "update_context_configuration", ContextID: a.ContextID, Configuration: a.Configuration})
	}),
	"set_context_grill_defaults": withArgs([]string{"contextId", "defaults"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64                     `json:"contextId"`
			Defaults  domain.GrillConfiguration `json:"defaults"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_context_grill_defaults", ContextID: a.ContextID, GrillConfiguration: a.Defaults})
	}),
	"set_context_implement_defaults": withArgs([]string{"contextId", "defaults"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64                     `json:"contextId"`
			Defaults  domain.GrillConfiguration `json:"defaults"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_context_implement_defaults", ContextID: a.ContextID, GrillConfiguration: a.Defaults})
	}),
	"set_context_dirty_checkout_check": withArgs([]string{"contextId", "enabled"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID int64 `json:"contextId"`
			Enabled   bool  `json:"enabled"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_context_dirty_checkout_check", ContextID: a.ContextID, Enabled: a.Enabled})
	}),
	"set_context_attention_default": withArgs([]string{"contextId", "objectKind", "policy"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ContextID  int64                       `json:"contextId"`
			ObjectKind domain.ExternalObjectKind   `json:"objectKind"`
			Policy     domain.ExternalChangePolicy `json:"policy"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_context_attention_default", ContextID: a.ContextID, ObjectKind: a.ObjectKind, Policy: a.Policy})
	}),
	"create_project": withArgs([]string{"name", "contextId", "defaultItemStatus"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Name              string                `json:"name"`
			ContextID         int64                 `json:"contextId"`
			DefaultItemStatus domain.ItemStatus     `json:"defaultItemStatus"`
			ExecutionMode     *domain.ExecutionMode `json:"executionMode"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		mode := domain.ExecutionWorktree
		if a.ExecutionMode != nil {
			mode = *a.ExecutionMode
		}
		return s.Runtime.runEvent(domain.Event{Kind: "create_project", Name: a.Name, ContextID: a.ContextID, Defaults: domain.ProjectDefaults{ItemStatus: a.DefaultItemStatus, ExecutionMode: mode}})
	}),
	"update_project": withArgs([]string{"projectId", "name", "defaultItemStatus"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ProjectID         int64                 `json:"projectId"`
			Name              string                `json:"name"`
			DefaultItemStatus domain.ItemStatus     `json:"defaultItemStatus"`
			ExecutionMode     *domain.ExecutionMode `json:"executionMode"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		mode := domain.ExecutionWorktree
		if a.ExecutionMode != nil {
			mode = *a.ExecutionMode
		}
		return s.Runtime.runEvent(domain.Event{Kind: "update_project", ProjectID: a.ProjectID, Name: a.Name, Defaults: domain.ProjectDefaults{ItemStatus: a.DefaultItemStatus, ExecutionMode: mode}})
	}),
	"create_item": withArgs([]string{"title", "contextId", "projectId", "notes"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			Title     string  `json:"title"`
			ContextID int64   `json:"contextId"`
			ProjectID int64   `json:"projectId"`
			Notes     *string `json:"notes"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		notes := ""
		if a.Notes != nil {
			notes = *a.Notes
		}
		return s.Runtime.runEvent(domain.Event{Kind: "create_item", Name: a.Title, ContextID: a.ContextID, ProjectID: a.ProjectID, Notes: notes})
	}),
	"set_item_status": withArgs([]string{"itemId", "status"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID int64             `json:"itemId"`
			Status domain.ItemStatus `json:"status"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_item_status", ItemID: a.ItemID, Status: a.Status})
	}),
	"set_item_title": withArgs([]string{"itemId", "title"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID int64  `json:"itemId"`
			Title  string `json:"title"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_item_title", ItemID: a.ItemID, Name: a.Title})
	}),
	"set_item_notes": withArgs([]string{"itemId", "notes"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID int64  `json:"itemId"`
			Notes  string `json:"notes"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_item_notes", ItemID: a.ItemID, Notes: a.Notes})
	}),
	"add_item_reminder": withArgs([]string{"itemId", "remindAt"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID   int64  `json:"itemId"`
			RemindAt string `json:"remindAt"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "add_item_reminder", ItemID: a.ItemID, RemindAt: a.RemindAt})
	}),
	"remove_item_reminder": withArgs([]string{"itemId", "reminderId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID     int64 `json:"itemId"`
			ReminderID int64 `json:"reminderId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "remove_item_reminder", ItemID: a.ItemID, ReminderID: a.ReminderID})
	}),
	"set_item_relation": withArgs([]string{"fromItemId", "toItemId", "kind"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			FromItemID int64                   `json:"fromItemId"`
			ToItemID   int64                   `json:"toItemId"`
			Kind       domain.ItemRelationKind `json:"kind"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_item_relation", FromItemID: a.FromItemID, ToItemID: a.ToItemID, RelationKind: a.Kind})
	}),
	"link_external_object": withArgs([]string{"itemId", "url"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID int64  `json:"itemId"`
			URL    string `json:"url"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.linkExternalObject(a.ItemID, a.URL)
	}),
	"create_github_issue": withArgs([]string{"itemId", "repositoryId", "title", "body"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ItemID       int64  `json:"itemId"`
			RepositoryID int64  `json:"repositoryId"`
			Title        string `json:"title"`
			Body         string `json:"body"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.createGithubIssue(a.ItemID, a.RepositoryID, a.Title, a.Body)
	}),
	"add_external_comment": withArgs([]string{"linkId", "body"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID int64  `json:"linkId"`
			Body   string `json:"body"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.addExternalComment(a.LinkID, a.Body)
	}),
	"fetch_issue_document": withArgs([]string{"externalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64 `json:"externalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.fetchIssueDocument(a.ExternalObjectID)
	}),
	"fetch_external_comments": withArgs([]string{"externalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64 `json:"externalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.fetchExternalComments(a.ExternalObjectID)
	}),
	"fetch_external_document": withArgs([]string{"externalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64 `json:"externalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.fetchExternalDocument(a.ExternalObjectID)
	}),
	"refresh_external_object": withArgs([]string{"externalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64 `json:"externalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.refreshExternalObject(a.ExternalObjectID)
	}),
	"set_link_attention_policy": withArgs([]string{"linkId", "policy"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID int64                          `json:"linkId"`
			Policy *domain.LinkAttentionOverrides `json:"policy"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_link_attention_policy", LinkID: a.LinkID, AttentionOverrides: a.Policy})
	}),
	"set_link_purpose": withArgs([]string{"linkId", "purpose", "specExternalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID               int64              `json:"linkId"`
			Purpose              domain.LinkPurpose `json:"purpose"`
			SpecExternalObjectID *int64             `json:"specExternalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_link_purpose", LinkID: a.LinkID, Purpose: a.Purpose, SpecExternalObjectID: a.SpecExternalObjectID})
	}),
	"set_link_watch_until": withArgs([]string{"linkId", "watchUntil"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID     int64   `json:"linkId"`
			WatchUntil *string `json:"watchUntil"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		value := ""
		if a.WatchUntil != nil {
			value = *a.WatchUntil
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_link_watch_until", LinkID: a.LinkID, Timestamp: value})
	}),
	"set_link_review_at": withArgs([]string{"linkId", "reviewAt"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID   int64   `json:"linkId"`
			ReviewAt *string `json:"reviewAt"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		value := ""
		if a.ReviewAt != nil {
			value = *a.ReviewAt
		}
		return s.Runtime.runEvent(domain.Event{Kind: "set_link_review_at", LinkID: a.LinkID, Timestamp: value})
	}),
	"clear_link_review_at": withArgs([]string{"linkId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID int64 `json:"linkId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "clear_link_review_at", LinkID: a.LinkID})
	}),
	"mark_link_reviewed": withArgs([]string{"linkId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID int64 `json:"linkId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.runEvent(domain.Event{Kind: "mark_link_reviewed", LinkID: a.LinkID})
	}),
	"unlink_external_link": withArgs([]string{"linkId", "confirmed"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			LinkID    int64 `json:"linkId"`
			Confirmed bool  `json:"confirmed"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.unlinkExternalLink(a.LinkID, a.Confirmed)
	}),
	"prepare_external_object_deletion": withArgs([]string{"externalObjectId"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64 `json:"externalObjectId"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.prepareExternalObjectDeletion(a.ExternalObjectID)
	}),
	"delete_external_object": withArgs([]string{"externalObjectId", "confirmed", "stateFingerprint"}, func(s *CommandService, raw json.RawMessage) (any, error) {
		var a struct {
			ExternalObjectID int64  `json:"externalObjectId"`
			Confirmed        bool   `json:"confirmed"`
			StateFingerprint string `json:"stateFingerprint"`
		}
		if e := decodeArgs(raw, &a); e != nil {
			return nil, e
		}
		return s.Runtime.deleteExternalObject(a.ExternalObjectID, a.Confirmed, a.StateFingerprint)
	}),
	"poll_external_objects": noArgs(func(s *CommandService) (any, error) { return s.Runtime.pollExternalObjects() }),
}

var registeredCommandArguments = map[string][]string{
	"get_setup_state": {}, "complete_setup": {"contextName", "provider"}, "get_health_status": {"provider"},
	"list_contexts": {}, "new_context_configuration": {}, "list_context_attention_defaults": {}, "list_projects": {}, "list_repositories": {}, "list_repository_locations": {}, "list_audit_history": {}, "get_activity_tab": {}, "list_grill_model_catalog": {}, "refresh_grill_model_catalog": {}, "list_plan_usage": {}, "refresh_plan_usage": {},
	"create_context": {"name"}, "create_context_configuration": {"configuration"}, "update_context": {"contextId", "name"}, "update_context_configuration": {"contextId", "configuration"},
	"set_context_grill_defaults": {"contextId", "defaults"}, "set_context_implement_defaults": {"contextId", "defaults"}, "set_context_dirty_checkout_check": {"contextId", "enabled"},
	"set_context_attention_default": {"contextId", "objectKind", "policy"}, "create_project": {"name", "contextId", "defaultItemStatus", "executionMode"}, "update_project": {"projectId", "name", "defaultItemStatus", "executionMode"},
	"register_repository": {"projectId", "name", "remoteUrl"}, "update_repository": {"repositoryId", "name", "remoteUrl", "baseBranch"}, "register_repository_at_location": {"projectId", "name", "remoteUrl", "baseBranch", "machineId", "checkoutPath", "worktreeRoot", "cloneIntoDestination"}, "update_repository_location": {"repositoryId", "previousMachineId", "machineId", "checkoutPath", "worktreeRoot"},
	"get_home": {"contextId", "now"}, "search_items_command": {"query", "contextId"}, "list_inbox_items": {}, "create_item": {"title", "contextId", "projectId", "notes"}, "set_item_status": {"itemId", "status"}, "set_item_title": {"itemId", "title"}, "set_item_notes": {"itemId", "notes"}, "add_item_reminder": {"itemId", "remindAt"}, "remove_item_reminder": {"itemId", "reminderId"}, "set_item_relation": {"fromItemId", "toItemId", "kind"},
	"link_external_object": {"itemId", "url"}, "create_github_issue": {"itemId", "repositoryId", "title", "body"}, "add_external_comment": {"linkId", "body"}, "fetch_issue_document": {"externalObjectId"}, "fetch_external_comments": {"externalObjectId"}, "fetch_external_document": {"externalObjectId"}, "refresh_external_object": {"externalObjectId"}, "poll_external_objects": {},
	"set_link_attention_policy": {"linkId", "policy"}, "set_link_purpose": {"linkId", "purpose", "specExternalObjectId"}, "set_link_watch_until": {"linkId", "watchUntil"}, "set_link_review_at": {"linkId", "reviewAt"}, "clear_link_review_at": {"linkId"}, "mark_link_reviewed": {"linkId"}, "unlink_external_link": {"linkId", "confirmed"}, "prepare_external_object_deletion": {"externalObjectId"}, "delete_external_object": {"externalObjectId", "confirmed", "stateFingerprint"},
}

func (s *CommandService) Invoke(command string, argsJSON string) (json.RawMessage, error) {
	args := json.RawMessage(argsJSON)
	if len(args) == 0 {
		args = json.RawMessage(`{}`)
	}
	handler, ok := commandHandlers[command]
	if !ok {
		return nil, fmt.Errorf("unknown command: %s", command)
	}
	return handler(s, args)
}
func noArgs(fn func(*CommandService) (any, error)) commandHandler {
	return func(s *CommandService, raw json.RawMessage) (json.RawMessage, error) {
		if err := requireEmptyObject(raw); err != nil {
			return nil, fmt.Errorf("invalid arguments: %w", err)
		}
		return encodeResult(fn(s))
	}
}
func withArgs(required []string, fn func(*CommandService, json.RawMessage) (any, error)) commandHandler {
	return func(s *CommandService, raw json.RawMessage) (json.RawMessage, error) {
		if err := requireKeys(raw, required); err != nil {
			return nil, fmt.Errorf("invalid arguments: %w", err)
		}
		value, err := fn(s, raw)
		return encodeResult(value, err)
	}
}
func encodeResult(value any, err error) (json.RawMessage, error) {
	if err != nil {
		return nil, err
	}
	if value == nil {
		return json.RawMessage("null"), nil
	}
	encoded, e := json.Marshal(value)
	if e != nil {
		return nil, fmt.Errorf("encode command result: %w", e)
	}
	return encoded, nil
}
func writable(s *CommandService) bool { return s != nil && s.Runtime != nil && s.Runtime.store != nil }
func decodeArgs(raw json.RawMessage, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		return errors.New("trailing JSON")
	}
	return nil
}
func requireKeys(raw json.RawMessage, required []string) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil {
		return err
	}
	if fields == nil {
		return errors.New("expected an object")
	}
	for _, key := range required {
		if _, ok := fields[key]; !ok {
			return fmt.Errorf("missing field %q", key)
		}
	}
	return nil
}
func requireEmptyObject(raw json.RawMessage) error {
	var args map[string]json.RawMessage
	if err := json.Unmarshal(raw, &args); err != nil {
		return err
	}
	if args == nil {
		return errors.New("expected an object")
	}
	if len(args) != 0 {
		return errors.New("command takes no arguments")
	}
	return nil
}
func defaultContextConfiguration() domain.ContextConfiguration {
	return domain.NewContextConfiguration()
}
