package main

import (
	"crypto/sha256"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type entry struct {
	path       string
	executable bool
	size       int64
}

func main() {
	root := filepath.Join("assets", "pstack")
	patches, err := os.ReadFile(filepath.Join(root, "PATCHES.md"))
	must(err)
	version, commit := upstream(string(patches))
	var entries []entry
	err = filepath.WalkDir(root, func(path string, item fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if item.IsDir() {
			return nil
		}
		info, err := item.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("unsupported pstack vendor entry %s", path)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		entries = append(entries, entry{filepath.ToSlash(rel), info.Mode().Perm()&0o111 != 0, info.Size()})
		return nil
	})
	must(err)
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })
	hash := sha256.New()
	for _, item := range entries {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(item.path)))
		must(err)
		hash.Write([]byte(item.path))
		hash.Write([]byte{0})
		var size [8]byte
		n := uint64(len(data))
		for i := 7; i >= 0; i-- {
			size[i] = byte(n)
			n >>= 8
		}
		hash.Write(size[:])
		hash.Write(data)
		if item.executable {
			hash.Write([]byte{1})
		} else {
			hash.Write([]byte{0})
		}
	}
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by go generate; DO NOT EDIT.\npackage pstack\n\nconst Version = %q\nconst UpstreamCommit = %q\nconst TreeHash = %q\n\nvar Files = []File{\n", version, commit, fmt.Sprintf("%x", hash.Sum(nil)))
	for _, item := range entries {
		fmt.Fprintf(&out, "{Path:%q, Executable:%t},\n", item.path, item.executable)
	}
	out.WriteString("}\n")
	formatted, err := format.Source([]byte(out.String()))
	must(err)
	must(os.WriteFile("manifest_generated.go", formatted, 0o644))
}

func upstream(source string) (string, string) {
	for _, line := range strings.Split(source, "\n") {
		if !strings.Contains(line, "Upstream source:") {
			continue
		}
		version := between(line, "version `", "`")
		commit := between(line, "commit `", "`")
		if version == "" || commit == "" {
			break
		}
		return version, commit
	}
	panic("PATCHES.md must contain a parseable Upstream source line")
}
func between(s, start, end string) string {
	index := strings.Index(s, start)
	if index < 0 {
		return ""
	}
	rest := s[index+len(start):]
	value, _, _ := strings.Cut(rest, end)
	return value
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
